"use client";
import {useCallback,useEffect,useState} from "react";
import {LayoutDashboard,Users,Network,Clock3,CalendarDays,WalletCards,BarChart3,Search,Plus,ChevronDown,Menu,ArrowRight,ArrowUpRight,Check,AlertCircle,Download,RefreshCw,X,UserRound,BriefcaseBusiness,MapPin,MoreHorizontal,Play,Timer,FileText,Building2,CheckCircle2,CalendarCheck,UserPlus,TrendingUp} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";

type Department={id:number;name:string;lead:string;location:string};
type Position={id:number;title:string;department_id:number;department_name:string;grade:string;base_salary_cents:number};
type Employee={id:number;employee_no:string;first_name:string;last_name:string;email:string;department_id:number;position_id:number;start_date:string;status:string;employment_type:string;monthly_salary_cents:number;department_name:string;position_title:string};
type Attendance={id:number;employee_id:number;employee_name:string;work_date:string;clock_in:string|null;clock_out:string|null;status:string};
type Leave={id:number;employee_id:number;employee_name:string;department_name:string;type:string;start_date:string;end_date:string;days:number;reason:string;status:string;created_at:string};
type Run={id:string;period:string;status:string;created_at:string;finalized_at:string|null;total_cents:number};
type PayItem={id:number;run_id:string;employee_id:number;employee_name:string;basic_cents:number;allowance_cents:number;deduction_cents:number;net_cents:number};
type Data={departments:Department[];positions:Position[];employees:Employee[];attendance:Attendance[];leaves:Leave[];runs:Run[];items:PayItem[]};
const empty:Data={departments:[],positions:[],employees:[],attendance:[],leaves:[],runs:[],items:[]};
const money=(c:number)=>"₱"+(c/100).toLocaleString("en-PH",{minimumFractionDigits:2,maximumFractionDigits:2});
const fmt=(d:string)=>new Date(d+"T00:00:00").toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"});
const name=(e:Employee)=>e.first_name+" "+e.last_name;
const initials=(s:string)=>s.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();
const localDay=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Manila"});
const month=()=>localDay().slice(0,7);
const pages=[
 {group:"WORKSPACE",items:[["Overview",LayoutDashboard],["Employees",Users],["Organization",Network]]},
 {group:"PEOPLE OPERATIONS",items:[["Attendance",Clock3],["Leave Requests",CalendarDays],["Payroll",WalletCards]]},
 {group:"INSIGHTS",items:[["Reports",BarChart3]]}
] as const;
const meta:Record<string,{eyebrow:string;title:string;description:string;action:string;modal:string}>={
 Overview:{eyebrow:"WORKSPACE / OVERVIEW",title:"Good day, HR team",description:"Here’s what’s happening across your people operations.",action:"Add employee",modal:"employee"},
 Employees:{eyebrow:"WORKSPACE / PEOPLE",title:"Employees",description:"Profiles, roles and employment details in one place.",action:"Add employee",modal:"employee"},
 Organization:{eyebrow:"WORKSPACE / STRUCTURE",title:"Organization",description:"Departments and positions that shape your team.",action:"Add department",modal:"department"},
 Attendance:{eyebrow:"PEOPLE OPERATIONS / TIME",title:"Attendance",description:"Track daily clock-ins and clock-outs.",action:"Record attendance",modal:"attendance"},
 "Leave Requests":{eyebrow:"PEOPLE OPERATIONS / LEAVE",title:"Leave requests",description:"Review time-off requests and record decisions.",action:"Request leave",modal:"leave"},
 Payroll:{eyebrow:"PEOPLE OPERATIONS / PAYROLL",title:"Payroll",description:"Generate monthly salary snapshots for your team.",action:"Create payroll run",modal:"payroll"},
 Reports:{eyebrow:"INSIGHTS / REPORTS",title:"People analytics",description:"Monitor headcount, attendance and leave activity.",action:"Export CSV",modal:"export"}
};
function Choice({label,value,onChange,options,placeholder="Select an option"}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];placeholder?:string}){return <Select value={value||undefined} onValueChange={v=>onChange(v||"")}><SelectTrigger className="choice" aria-label={label}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function Stat({label,value,detail,icon:Icon,tone}:{label:string;value:string;detail:string;icon:typeof Users;tone:string}){return <div className="stat"><div className="stat-top"><span>{label}</span><i className={tone}><Icon size={19}/></i></div><strong>{value}</strong><small>{detail}</small></div>}
function Empty({title,detail}:{title:string;detail:string}){return <div className="empty-state"><FileText size={27}/><b>{title}</b><span>{detail}</span></div>}
export default function Home(){
 const [view,V]=useState("Overview"),[data,S]=useState<Data>(empty),[loading,L]=useState(true),[busy,B]=useState(false),[error,E]=useState(""),[notice,N]=useState(""),[dialog,D]=useState(""),[draft,F]=useState<Record<string,string>>({}),[search,Q]=useState(""),[filter,K]=useState("All"),[menu,U]=useState(false),[selectedRun,R]=useState<Run|null>(null);
 const reload=useCallback(async()=>{try{const r=await fetch("/api/hris",{cache:"no-store"}),j=await r.json() as Data&{error?:string};if(!r.ok)throw Error(j.error||"Could not load HRIS records.");S(j);E("")}catch(e){E(e instanceof Error?e.message:"Could not load records.")}finally{L(false)}},[]);
 useEffect(()=>{void reload()},[reload]);
 const mutate=async(body:Record<string,unknown>)=>{B(true);E("");try{const r=await fetch("/api/hris",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json() as {message?:string;error?:string};if(!r.ok)throw Error(j.error||"Unable to save.");N(j.message||"Saved.");D("");F({});await reload();return true}catch(e){E(e instanceof Error?e.message:"Unable to save.");return false}finally{B(false)}};
 const go=(p:string)=>{V(p);Q("");K("All");U(false);N("");E("")};
 const open=(type:string,values:Record<string,string>={})=>{F(values);D(type);E("")};
 const active=data.employees.filter(e=>e.status==="Active"),pending=data.leaves.filter(l=>l.status==="Pending"),today=localDay(),presentToday=data.attendance.filter(a=>a.work_date===today).length,monthlyBase=active.reduce((n,e)=>n+e.monthly_salary_cents,0);
 const matchingEmployees=data.employees.filter(e=>`${e.employee_no} ${name(e)} ${e.position_title} ${e.department_name}`.toLowerCase().includes(search.toLowerCase())&&(filter==="All"||e.status===filter));
 const matchingLeaves=data.leaves.filter(l=>`${l.employee_name} ${l.type} ${l.department_name}`.toLowerCase().includes(search.toLowerCase())&&(filter==="All"||l.status===filter));
 const matchingAttendance=data.attendance.filter(a=>`${a.employee_name} ${a.work_date}`.toLowerCase().includes(search.toLowerCase())&&(filter==="All"||filter==="Today"&&a.work_date===today));
 const chosenPositions=data.positions.filter(p=>p.department_id===Number(draft.departmentId));
 const tab=meta[view];
 const errorBox=error?<div className="error-box" role="alert"><AlertCircle size={16}/>{error}</div>:null;
 const required=(keys:string[])=>keys.every(k=>draft[k]?.trim());
 const save=()=>{
  if(dialog==="department"){if(!required(["name"])){E("Enter a department name.");return}void mutate({action:"department",...draft});return}
  if(dialog==="position"){if(!required(["title","departmentId"])){E("Enter a title and department.");return}const base=Number(draft.baseSalary||0);if(!Number.isFinite(base)||base<0){E("Enter a valid monthly salary.");return}void mutate({action:"position",title:draft.title,departmentId:Number(draft.departmentId),grade:draft.grade||"",baseSalaryCents:Math.round(base*100)});return}
  if(dialog==="employee"||dialog==="editEmployee"){if(!required(["employeeNo","firstName","lastName","email","departmentId","positionId","startDate","salary"])){E("Complete all required employee fields.");return}const salary=Number(draft.salary);if(!Number.isFinite(salary)||salary<0){E("Enter a valid salary.");return}void mutate({action:dialog==="employee"?"employee":"updateEmployee",id:Number(draft.id||0),employeeNo:draft.employeeNo,firstName:draft.firstName,lastName:draft.lastName,email:draft.email,departmentId:Number(draft.departmentId),positionId:Number(draft.positionId),startDate:draft.startDate,status:draft.status||"Active",employmentType:draft.employmentType||"Regular",monthlySalaryCents:Math.round(salary*100)});return}
  if(dialog==="attendance"){if(!required(["employeeId","event"])){E("Select an employee and clock action.");return}void mutate({action:"clock",employeeId:Number(draft.employeeId),workDate:today,event:draft.event});return}
  if(dialog==="leave"){if(!required(["employeeId","type","startDate","endDate"])){E("Complete the leave request.");return}void mutate({action:"leave",employeeId:Number(draft.employeeId),type:draft.type,startDate:draft.startDate,endDate:draft.endDate,reason:draft.reason||""});return}
  if(dialog==="payroll"){void mutate({action:"payroll",period:draft.period||month()});return}
 };
 const exportCsv=()=>{const rows=[["Employee No","Name","Department","Position","Status","Employment Type","Start Date"],...data.employees.map(e=>[e.employee_no,name(e),e.department_name,e.position_title,e.status,e.employment_type,e.start_date])];const cell=(v:string)=>'"'+v.replaceAll('"','""')+'"';const blob=new Blob([rows.map(r=>r.map(cell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="peopleflow-headcount.csv";a.click();URL.revokeObjectURL(url)};
 const edit=(e:Employee)=>open("editEmployee",{id:String(e.id),employeeNo:e.employee_no,firstName:e.first_name,lastName:e.last_name,email:e.email,departmentId:String(e.department_id),positionId:String(e.position_id),startDate:e.start_date,status:e.status,employmentType:e.employment_type,salary:String(e.monthly_salary_cents/100)});
 const noData=!loading&&!data.departments.length&&!data.employees.length;
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();void Promise.resolve(ctx.registerTool({name:"read_hris_overview",title:"Read HRIS overview",description:"Read current headcount, pending leave and attendance totals from the workspace.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {employees:data.employees.length,activeEmployees:active.length,pendingLeave:pending.length,presentToday,departments:data.departments.length}}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort()},[data,active.length,pending.length,presentToday]);
 return <div className="shell"><aside className={`sidebar ${menu?"open":""}`}><div className="brand"><div className="brand-icon"><span>✳</span></div><div><strong>peopleflow<span>.</span></strong><small>HUMAN RESOURCES</small></div></div><button className="workspace"><div>PF</div><span><b>PeopleFlow HQ</b><small>Main workspace</small></span><ChevronDown size={15}/></button><nav>{pages.map(section=><div className="nav-section" key={section.group}><p>{section.group}</p>{section.items.map(([title,Icon])=><button className={view===title?"active":""} key={title} onClick={()=>go(title)}><Icon size={18}/><span>{title}</span>{title==="Leave Requests"&&pending.length>0&&<em>{pending.length}</em>}</button>)}</div>)}</nav><div className="sidebar-footer"><div className="mini-help"><div><CheckCircle2 size={18}/><strong>People at the center</strong></div><p>Keep your team's records connected and up to date.</p></div><div className="user"><span className="user-avatar">HR</span><div><b>HR Administrator</b><small>Workspace owner</small></div><MoreHorizontal size={17}/></div></div></aside>{menu&&<button className="shade" aria-label="Close navigation" onClick={()=>U(false)}/>}
 <main className="main"><header className="topbar"><div className="crumb"><button className="menu-button" aria-label="Open navigation" onClick={()=>U(true)}><Menu size={21}/></button><span>Workspace</span><span>/</span><b>{view}</b></div><div className="top-right"><span>{new Date().toLocaleDateString("en-PH",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</span><i/><span className="top-avatar">HR</span></div></header><div className="content"><div className="heading"><div><p className="eyebrow">{tab.eyebrow}</p><h1>{tab.title}</h1><p>{tab.description}</p></div><button className="primary" onClick={()=>tab.modal==="export"?exportCsv():open(tab.modal)}>{tab.modal==="export"?<Download size={16}/>:<Plus size={17}/>} {tab.action}</button></div>{error&&!dialog&&<div className="banner-error" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>void reload()}><RefreshCw size={15}/> Retry</button></div>}{notice&&<div className="banner-success" role="status"><Check size={17}/><span>{notice}</span><button aria-label="Dismiss" onClick={()=>N("")}><X size={15}/></button></div>}
 {loading?<div className="loading">Loading people records…</div>:<>{noData&&<div className="starter"><div className="starter-icon"><UserPlus size={26}/></div><div><b>Welcome to your people workspace</b><p>Add your own departments and positions first, or load sample records to explore attendance, leave and payroll.</p></div><button disabled={busy} onClick={()=>void mutate({action:"seed"})}>Load sample data <ArrowRight size={16}/></button></div>}
 {view==="Overview"&&<><div className="metrics"><Stat label="Total employees" value={String(data.employees.length)} detail={active.length+" currently active"} icon={Users} tone="coral"/><Stat label="Present today" value={String(presentToday)} detail="Recorded attendance" icon={Clock3} tone="blue"/><Stat label="Pending leave" value={String(pending.length)} detail="Requests to review" icon={CalendarDays} tone="gold"/><Stat label="Monthly base pay" value={money(monthlyBase)} detail="Active employees only" icon={WalletCards} tone="purple"/></div><div className="overview-grid"><section className="panel people-card"><div className="panel-heading"><div><h2>Your team</h2><p>People across your organization</p></div><button onClick={()=>go("Employees")}>View all <ArrowRight size={15}/></button></div><div className="team-preview">{data.employees.slice(0,5).map(e=><div className="team-row" key={e.id}><span className="face">{initials(name(e))}</span><div><b>{name(e)}</b><small>{e.position_title} · {e.department_name}</small></div><span className={e.status==="Active"?"badge green":"badge amber"}>{e.status}</span></div>)}{!data.employees.length&&<Empty title="No employees yet" detail="Add an employee to populate your directory."/>}</div></section><section className="panel leave-card"><div className="panel-heading"><div><h2>Leave to review</h2><p>Requests awaiting a decision</p></div><button onClick={()=>go("Leave Requests")}>Review all <ArrowRight size={15}/></button></div>{pending.slice(0,4).map(l=><div className="leave-preview" key={l.id}><span className="face muted">{initials(l.employee_name)}</span><div><b>{l.employee_name}</b><small>{l.type} · {fmt(l.start_date)} – {fmt(l.end_date)}</small></div><span>{l.days}d</span></div>)}{!pending.length&&<div className="calm-empty"><CalendarCheck size={27}/><strong>All caught up</strong><span>No leave requests need review.</span></div>}</section></div><div className="overview-bottom"><div className="tip"><div className="tip-icon"><TrendingUp size={20}/></div><div><b>Attendance at a glance</b><p>{data.employees.length?Math.round(presentToday/data.employees.length*100):0}% of your team has an attendance record for today.</p></div><button onClick={()=>go("Attendance")}>View attendance <ArrowRight size={15}/></button></div></div></>}
 {view==="Employees"&&<section className="panel table-panel"><div className="table-tools"><div><h2>Employee directory</h2><span>{matchingEmployees.length} team members</span></div><div className="tools-right"><div className="search"><Search size={17}/><input value={search} onChange={e=>Q(e.target.value)} placeholder="Search people..." aria-label="Search employees"/></div><Choice label="Status filter" value={filter} onChange={K} options={["All","Active","On leave","Inactive"].map(v=>({value:v,label:v}))}/></div></div><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Employee ID</TableHead><TableHead>Department</TableHead><TableHead>Position</TableHead><TableHead>Start date</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{matchingEmployees.map(e=><TableRow key={e.id}><TableCell><div className="person-cell"><span className="face">{initials(name(e))}</span><span><b>{name(e)}</b><small>{e.email}</small></span></div></TableCell><TableCell className="mono">{e.employee_no}</TableCell><TableCell>{e.department_name}</TableCell><TableCell>{e.position_title}</TableCell><TableCell>{fmt(e.start_date)}</TableCell><TableCell><span className={e.status==="Active"?"badge green":"badge amber"}>{e.status}</span></TableCell><TableCell><button className="table-action" onClick={()=>edit(e)}>Edit <ArrowRight size={13}/></button></TableCell></TableRow>)}</TableBody></Table>{!matchingEmployees.length&&<Empty title="No employees found" detail="Add someone or change your search."/>}</section>}
 {view==="Organization"&&<><div className="org-intro"><div><span>ORGANIZATION STRUCTURE</span><h2>{data.departments.length} departments <i>·</i> {data.positions.length} positions</h2><p>Positions belong to departments, keeping every employee aligned with your org chart.</p></div><button onClick={()=>open("position")}><Plus size={16}/> Add position</button></div><div className="department-grid">{data.departments.map(d=><div className="department-card" key={d.id}><div className="dept-head"><span><Building2 size={19}/></span><em>{data.employees.filter(e=>e.department_id===d.id).length} people</em></div><h3>{d.name}</h3><p><UserRound size={15}/> {d.lead||"No lead assigned"}</p><p><MapPin size={15}/> {d.location||"No location"}</p><div className="dept-positions">{data.positions.filter(p=>p.department_id===d.id).map(p=><span key={p.id}>{p.title}</span>)}</div></div>)}</div>{!data.departments.length&&<Empty title="No departments yet" detail="Create a department, then add positions and employees."/>}</>}
 {view==="Attendance"&&<section className="panel table-panel"><div className="table-tools"><div><h2>Daily attendance</h2><span>{matchingAttendance.length} records</span></div><div className="tools-right"><div className="search"><Search size={17}/><input aria-label="Search attendance" placeholder="Search name or date..." value={search} onChange={e=>Q(e.target.value)}/></div><Choice label="Date filter" value={filter} onChange={K} options={["All","Today"].map(v=>({value:v,label:v}))}/></div></div><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Work date</TableHead><TableHead>Clock in</TableHead><TableHead>Clock out</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{matchingAttendance.map(a=><TableRow key={a.id}><TableCell><div className="person-cell"><span className="face">{initials(a.employee_name)}</span><b>{a.employee_name}</b></div></TableCell><TableCell>{fmt(a.work_date)}</TableCell><TableCell>{a.clock_in?new Date(a.clock_in).toLocaleTimeString("en-PH",{hour:"numeric",minute:"2-digit"}):"—"}</TableCell><TableCell>{a.clock_out?new Date(a.clock_out).toLocaleTimeString("en-PH",{hour:"numeric",minute:"2-digit"}):"—"}</TableCell><TableCell><span className="badge green">Present</span></TableCell></TableRow>)}</TableBody></Table>{!matchingAttendance.length&&<Empty title="No attendance records" detail="Record a clock-in to begin tracking time."/>}</section>}
 {view==="Leave Requests"&&<section className="panel table-panel"><div className="table-tools"><div><h2>Time-off requests</h2><span>{matchingLeaves.length} requests</span></div><div className="tools-right"><div className="search"><Search size={17}/><input aria-label="Search leave requests" placeholder="Search people or leave type..." value={search} onChange={e=>Q(e.target.value)}/></div><Choice label="Leave status" value={filter} onChange={K} options={["All","Pending","Approved","Rejected"].map(v=>({value:v,label:v}))}/></div></div><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Leave type</TableHead><TableHead>Dates</TableHead><TableHead>Duration</TableHead><TableHead>Reason</TableHead><TableHead>Status</TableHead><TableHead>Decision</TableHead></TableRow></TableHeader><TableBody>{matchingLeaves.map(l=><TableRow key={l.id}><TableCell><div className="person-cell"><span className="face">{initials(l.employee_name)}</span><span><b>{l.employee_name}</b><small>{l.department_name}</small></span></div></TableCell><TableCell>{l.type}</TableCell><TableCell>{fmt(l.start_date)} – {fmt(l.end_date)}</TableCell><TableCell>{l.days} day{l.days===1?"":"s"}</TableCell><TableCell className="reason-cell" title={l.reason}>{l.reason||"—"}</TableCell><TableCell><span className={l.status==="Approved"?"badge green":l.status==="Rejected"?"badge red":"badge amber"}>{l.status}</span></TableCell><TableCell>{l.status==="Pending"?<div className="decisions"><button disabled={busy} className="approve" onClick={()=>void mutate({action:"leaveDecision",id:l.id,decision:"Approved"})} aria-label={`Approve leave for ${l.employee_name}`}><Check size={15}/></button><button disabled={busy} className="reject" onClick={()=>void mutate({action:"leaveDecision",id:l.id,decision:"Rejected"})} aria-label={`Reject leave for ${l.employee_name}`}><X size={15}/></button></div>:<span className="muted-dash">—</span>}</TableCell></TableRow>)}</TableBody></Table>{!matchingLeaves.length&&<Empty title="No requests found" detail="Submit a leave request or change your search."/>}</section>}
 {view==="Payroll"&&<><div className="payroll-explainer"><div><WalletCards size={24}/><div><b>Monthly salary snapshots</b><p>Draft runs use each active employee’s monthly base salary. Statutory deductions, taxes and allowances are not calculated.</p></div></div><span>{active.length} eligible employees</span></div><section className="panel table-panel"><div className="table-tools"><div><h2>Payroll runs</h2><span>{data.runs.length} periods</span></div></div><Table><TableHeader><TableRow><TableHead>Period</TableHead><TableHead>Created</TableHead><TableHead>Employees</TableHead><TableHead>Gross base total</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{data.runs.map(r=><TableRow key={r.id}><TableCell><b>{new Date(r.period+"-01T00:00:00").toLocaleDateString("en-PH",{month:"long",year:"numeric"})}</b></TableCell><TableCell>{fmt(r.created_at.slice(0,10))}</TableCell><TableCell>{data.items.filter(i=>i.run_id===r.id).length}</TableCell><TableCell><b>{money(r.total_cents)}</b></TableCell><TableCell><span className={r.status==="Finalized"?"badge green":"badge amber"}>{r.status}</span></TableCell><TableCell><div className="row-actions"><button onClick={()=>R(r)}>View details</button>{r.status==="Draft"&&<button disabled={busy} onClick={()=>void mutate({action:"finalizePayroll",id:r.id})}>Finalize <ArrowRight size={13}/></button>}</div></TableCell></TableRow>)}</TableBody></Table>{!data.runs.length&&<Empty title="No payroll runs" detail="Create a monthly draft after adding active employees."/>}</section></>}
 {view==="Reports"&&<><div className="metrics"><Stat label="Headcount" value={String(data.employees.length)} detail={active.length+" active employees"} icon={Users} tone="coral"/><Stat label="Departments" value={String(data.departments.length)} detail="Across the organization" icon={Network} tone="blue"/><Stat label="Attendance today" value={String(presentToday)} detail="Recorded check-ins" icon={Clock3} tone="gold"/><Stat label="Approved leave" value={String(data.leaves.filter(l=>l.status==="Approved").length)} detail="Approved requests" icon={CalendarCheck} tone="purple"/></div><div className="report-grid"><section className="panel"><div className="panel-heading"><div><h2>Headcount by department</h2><p>Distribution of all employee profiles</p></div></div><div className="report-bars">{data.departments.map(d=>{const count=data.employees.filter(e=>e.department_id===d.id).length;return <div className="bar-row" key={d.id}><div><b>{d.name}</b><span>{count} {count===1?"person":"people"}</span></div><div className="bar-track"><i style={{width:`${Math.round(count/Math.max(1,...data.departments.map(x=>data.employees.filter(e=>e.department_id===x.id).length))*100)}%`}}/></div></div>})}{!data.departments.length&&<Empty title="No departments" detail="Add departments to see the headcount chart."/>}</div></section><section className="panel"><div className="panel-heading"><div><h2>Leave activity</h2><p>Requests by status</p></div></div><div className="report-summary">{["Pending","Approved","Rejected"].map(status=><div key={status}><span className={`small-dot ${status.toLowerCase()}`}/><b>{status}</b><strong>{data.leaves.filter(l=>l.status===status).length}</strong></div>)}</div></section></div></>}
 </>}</div></main>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v){D("");E("")}}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{({department:"Add department",position:"Add position",employee:"Add employee",editEmployee:"Edit employee",attendance:"Record attendance",leave:"Request leave",payroll:"Create payroll run"} as Record<string,string>)[dialog]||"New record"}</DialogTitle><DialogDescription>{dialog==="payroll"?"Generate a draft snapshot for all active employees.":dialog==="attendance"?"Record today's clock-in or clock-out.":"Enter the details below to update your workspace."}</DialogDescription></DialogHeader>{errorBox}<div className="form-grid">
 {dialog==="department"&&<><Field label="Department name" value={draft.name} onChange={v=>F({...draft,name:v})} required/><Field label="Department lead" value={draft.lead} onChange={v=>F({...draft,lead:v})}/><Field label="Location" value={draft.location} onChange={v=>F({...draft,location:v})}/></>}
 {dialog==="position"&&<><Field label="Position title" value={draft.title} onChange={v=>F({...draft,title:v})} required/><label className="field">Department<Choice label="Department" value={draft.departmentId||""} onChange={v=>F({...draft,departmentId:v})} options={data.departments.map(d=>({value:String(d.id),label:d.name}))}/></label><Field label="Grade" value={draft.grade} onChange={v=>F({...draft,grade:v})}/><Field label="Base monthly salary (₱)" type="number" value={draft.baseSalary} onChange={v=>F({...draft,baseSalary:v})}/></>}
 {(dialog==="employee"||dialog==="editEmployee")&&<><Field label="Employee number" value={draft.employeeNo} onChange={v=>F({...draft,employeeNo:v})} required/><Field label="Work email" type="email" value={draft.email} onChange={v=>F({...draft,email:v})} required/><Field label="First name" value={draft.firstName} onChange={v=>F({...draft,firstName:v})} required/><Field label="Last name" value={draft.lastName} onChange={v=>F({...draft,lastName:v})} required/><label className="field">Department<Choice label="Employee department" value={draft.departmentId||""} onChange={v=>F({...draft,departmentId:v,positionId:""})} options={data.departments.map(d=>({value:String(d.id),label:d.name}))}/></label><label className="field">Position<Choice label="Employee position" value={draft.positionId||""} onChange={v=>F({...draft,positionId:v})} options={chosenPositions.map(p=>({value:String(p.id),label:p.title}))}/></label><Field label="Start date" type="date" value={draft.startDate} onChange={v=>F({...draft,startDate:v})} required/><Field label="Monthly base salary (₱)" type="number" value={draft.salary} onChange={v=>F({...draft,salary:v})} required/><label className="field">Employment type<Choice label="Employment type" value={draft.employmentType||"Regular"} onChange={v=>F({...draft,employmentType:v})} options={["Regular","Probationary","Contractual","Part-time"].map(x=>({value:x,label:x}))}/></label><label className="field">Status<Choice label="Employee status" value={draft.status||"Active"} onChange={v=>F({...draft,status:v})} options={["Active","On leave","Inactive"].map(x=>({value:x,label:x}))}/></label></>}
 {dialog==="attendance"&&<><label className="field">Employee<Choice label="Employee" value={draft.employeeId||""} onChange={v=>F({...draft,employeeId:v})} options={active.map(e=>({value:String(e.id),label:name(e)}))}/></label><label className="field">Action<Choice label="Clock action" value={draft.event||""} onChange={v=>F({...draft,event:v})} options={[{value:"in",label:"Clock in"},{value:"out",label:"Clock out"}]}/></label><div className="form-note full"><Timer size={17}/> Recording for today, {fmt(today)}. The current time is captured when saved.</div></>}
 {dialog==="leave"&&<><label className="field">Employee<Choice label="Leave employee" value={draft.employeeId||""} onChange={v=>F({...draft,employeeId:v})} options={data.employees.map(e=>({value:String(e.id),label:name(e)}))}/></label><label className="field">Leave type<Choice label="Leave type" value={draft.type||""} onChange={v=>F({...draft,type:v})} options={["Vacation","Sick","Emergency","Unpaid"].map(x=>({value:x,label:x}))}/></label><Field label="Start date" type="date" value={draft.startDate} onChange={v=>F({...draft,startDate:v})} required/><Field label="End date" type="date" value={draft.endDate} onChange={v=>F({...draft,endDate:v})} required/><div className="full"><Field label="Reason (optional)" value={draft.reason} onChange={v=>F({...draft,reason:v})}/></div><div className="form-note full"><CalendarDays size={16}/> Duration is counted in calendar days. Leave balances are not deducted automatically.</div></>}
 {dialog==="payroll"&&<><Field label="Payroll month" type="month" value={draft.period||month()} onChange={v=>F({...draft,period:v})} required/><div className="form-note"><Users size={17}/> {active.length} active employees</div><div className="payroll-preview full"><span>Estimated gross base pay</span><strong>{money(monthlyBase)}</strong></div><div className="form-note full"><AlertCircle size={17}/> No tax, benefits or statutory deductions are applied. Review before finalizing.</div></>}
 </div><div className="form-actions"><button className="cancel" onClick={()=>{D("");E("")}}>Cancel</button><button className="primary" disabled={busy} onClick={save}>{busy?"Saving…":dialog==="payroll"?"Generate draft":dialog==="editEmployee"?"Save changes":"Save record"} <ArrowRight size={16}/></button></div></DialogContent></Dialog>
 <Dialog open={!!selectedRun} onOpenChange={v=>!v&&R(null)}><DialogContent className="details-dialog"><DialogHeader><DialogTitle>Payroll details</DialogTitle><DialogDescription>{selectedRun?.period} · {selectedRun?.status} · Base salary snapshot</DialogDescription></DialogHeader><div className="payroll-items"><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Basic</TableHead><TableHead>Net snapshot</TableHead></TableRow></TableHeader><TableBody>{data.items.filter(i=>i.run_id===selectedRun?.id).map(i=><TableRow key={i.id}><TableCell>{i.employee_name}</TableCell><TableCell>{money(i.basic_cents)}</TableCell><TableCell><b>{money(i.net_cents)}</b></TableCell></TableRow>)}</TableBody></Table></div><div className="payroll-detail-total"><span>Total</span><strong>{money(selectedRun?.total_cents||0)}</strong></div></DialogContent></Dialog>
 </div>;
}
function Field({label,value,onChange,type="text",required=false}:{label:string;value?:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="field">{label}{required&&<span className="required"> *</span>}<input type={type} required={required} min={type==="number"?"0":undefined} step={type==="number"?"0.01":undefined} value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
